added index.html
Kartaviy-arteom/2101513-device-34 pull request #1
Opened 2022-07-16 15:39 UTC by Grikus

+ modal window
+ catalog window in header

2022-07-17 09:41 UTC, Kartaviy-arteom requested changes

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +    <meta charset="utf-8" />
meta не требует закрытия
подробнее тут https://css-live.ru/verstka/do-not-close-tags.html

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +        <div class="header-background">
похоже на лишний div
н уверен что он тебе будет нужен

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +              <input class="search-field" id="search" type="search" />
legend это заголовок для fieldset
тут тебе нужен связанный с input label

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +              </li>
список ссылок

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +            <span class="products-catalog">Каталог товаров</span>
это ссылка на каталог

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +            <button class="products-catalog-button" area-label="открыть окно с категориями товаров.">+</button>
+ - svg, aria-label/ хороший тон указывать кнопкам тип

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +          </a>
кнопки внутри ссылки

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +      <section class="hot-offers">
это уже в main
последовательность заголовков: h2 выше h1

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +        </nav>
лучше обойтись одним nav на странице

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +          </h2>
это не заголовок

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +        </div>
может быть таблицей, списком

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +          <div class="offers-details-points">...</div>
что это?

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +          <h2 class="visually-hidden">Блок о доставке.</h2>
это блок не только о доставке. Это часто называют табами. Ты слева выбираешь доставку, гарантия, кредит, а справа для них меняется текст. Можно сделать по-разному но ссылки не нужны

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +            <h2 class="second title about-title">О нас</h2>
зачем здесь два h2?

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +          <div class="contacts-block">
лучше section

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +              +7 (812) 812-12-12
телефон ссылка

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +            </legend>
legend тут не валиден 
https://developer.mozilla.org/ru/docs/Learn/Forms/How_to_structure_a_web_form

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +            <input class="subscribe-field" id="subscribe" type="email" placeholder="Ваш e-mail" required />
label

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +            <img class="modal-picture" />
декоративная графика

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +          </nav>
тебе не обязательно все ссылки объединять в nav

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +          <span class="divider"></span>
для этого не нужен элемент в разметке

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +              </div>
зачем эту кнопу оборачивать в div?

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +              <input class="field count-field" type="number" id="count" name="counts" placeholder="1" required/>
label

2022-07-17 09:41 UTC, Kartaviy-arteom commented on index.html
> +                <a class="social-telegram" href="https://t.me/htmlacademy">
ссылкам на сторонние ресурсы лучше добавлять target="_blank"

2022-07-24 11:43 UTC, Grikus commented on index.html
> +    <meta charset="utf-8" />
исправил

2022-07-24 11:43 UTC, Grikus commented on index.html
> +        <div class="header-background">
оставил, нужен оказался

2022-07-24 11:43 UTC, Grikus commented on index.html
> +              <input class="search-field" id="search" type="search" />
исправил

2022-07-24 11:43 UTC, Grikus commented on index.html
> +              </li>
исправил

2022-07-24 11:43 UTC, Grikus commented on index.html
> +            <span class="products-catalog">Каталог товаров</span>
исправил

2022-07-24 11:43 UTC, Grikus commented on index.html
> +          </nav>
исправил

2022-07-24 11:43 UTC, Grikus commented on index.html
> +          <span class="divider"></span>
исправил

2022-07-24 11:43 UTC, Grikus commented on index.html
> +              </div>
исправил

2022-07-24 11:44 UTC, Grikus commented on index.html
> +              <input class="field count-field" type="number" id="count" name="counts" placeholder="1" required/>
исправил

2022-07-24 11:44 UTC, Grikus commented on index.html
> +                <a class="social-telegram" href="https://t.me/htmlacademy">
исправил

2022-07-27 07:19 UTC, Kartaviy-arteom requested changes

2022-07-27 07:19 UTC, Kartaviy-arteom commented on index.html
> +    <link rel="stylesheet" href="./styles/styles.css" />
при использовании сервера точка не обязательна вначале` href="./styles/styles.css"`, можно и так ` href="/styles/styles.css"`,
/ корень текущего диска;
./текущий каталог;

2022-07-27 07:19 UTC, Kartaviy-arteom commented on index.html
> +            </svg>
current color было в данном случае не указывать, у тебя в стайлгайде меняется только прозрачность

2022-07-27 07:19 UTC, Kartaviy-arteom commented on index.html
> +      <div class="section-container">
тут я не понял для чего тебе именно два контейнера, почему не может быть один
на `section-container` добавлен display:grid, но для чего не понятно

2022-07-27 07:19 UTC, Kartaviy-arteom commented on index.html
> +          <div class="header-background">
если этот элемент только для фона, он не нужен

2022-07-27 07:19 UTC, Kartaviy-arteom commented on index.html
> +            <div class="header-first-column">
лучше именовать классы от назначения, чем от внешнего вида. у тебя могут быть классы для примесей какич-то свойств. в препроцессорах для них добавятся mixin

2022-07-27 07:19 UTC, Kartaviy-arteom commented on index.html
> +                <button class="search-button">Найти</button>
type submit

2022-07-27 07:19 UTC, Kartaviy-arteom commented on index.html
> +            <nav class="header-second-column">
я бы сказал главная навигация на сайте: каталог, доставка, гарантия, контакты. Пользовательскую можно в nav не включать

2022-07-27 07:19 UTC, Kartaviy-arteom commented on index.html
> +      </div>
там у тебя 3 слайда. и там чуть другая разметка нужна. Есть пример слайдера в курсе

2022-07-27 07:19 UTC, Kartaviy-arteom commented on index.html
> +        <h1 class="visually-hidden">
у тебя есть критерий про иерархию заголовков, h2 не должен появляться раньше h1

2022-07-27 07:19 UTC, Kartaviy-arteom commented on index.html
> +                  alt="виртуальная реальность.">
я бы сказал что это декоративные изображение, alt дублируешь подпись снизу https://up.htmlacademy.ru/htmlcss/34/criteries#ALLY

2022-07-27 07:19 UTC, Kartaviy-arteom commented on index.html
> +            <div class="visually-hidden guarantee-description description">
здесь тебе не нужно прятать их через visually-hidden

2022-07-27 07:19 UTC, Kartaviy-arteom commented on index.html
> +        <section class="section-modal">
это может быть кнопка, но одна. да и секция с заголовком тут перебор

2022-07-27 07:19 UTC, Kartaviy-arteom commented on index.html
> +        </section>
это див внутри которого две секции

2022-07-27 07:19 UTC, Kartaviy-arteom commented on index.html
> +            <button class="subscribe-button">Подписаться</button>
submit

2022-07-27 07:19 UTC, Kartaviy-arteom commented on index.html
> +        <div class="footer-first-column">
тебе не нужен класс, которые описывает номер колонки и далее

2022-07-27 07:19 UTC, Kartaviy-arteom commented on styles/styles.css
> +}
фон и паддинг верхний можно все перенести сюда.
Высота хедера на индексе и каталоге одинакова. сейчас он слишком большой

2022-07-27 07:19 UTC, Kartaviy-arteom commented on styles/styles.css
> +  z-index: 0;
margin-top: -35px;
 и фон тут излишни

2022-07-27 07:19 UTC, Kartaviy-arteom commented on styles/styles.css
> +}
часть не кликабельна, перекрывается другим элементом

2022-07-27 07:19 UTC, Kartaviy-arteom commented on styles/styles.css
> +.slider-pagination {
будет позиционироваться абсолютно от низа слайдера

2022-07-27 07:19 UTC, Kartaviy-arteom commented on styles/styles.css
> +.footer-first-column {
если тебе нужны колонки  и строки, у тебя есть grid

2022-07-27 07:19 UTC, Kartaviy-arteom commented on styles/styles.css
> +  margin-bottom: 75px;
для чего это?

2022-07-27 07:19 UTC, Kartaviy-arteom commented on styles/styles.css
> +  height: 319px;
высота должна зависить от высоты списка

2022-07-27 07:19 UTC, Kartaviy-arteom commented on styles/styles.css
> +}
размер активной области

2022-07-27 07:19 UTC, Kartaviy-arteom commented on styles/styles.css
> +  padding: 7px 53px;
тебе не нужно зажимать текст паддингами. задай кнопке ширину.

2022-07-27 07:19 UTC, Kartaviy-arteom commented on styles/styles.css
> +  content: "01";
сейчас тебе нужно для каждого слайда передавать в стили контент, будет проще оставить номер в разметке

2022-07-27 10:18 UTC, Grikus commented on index.html
> +    <link rel="stylesheet" href="./styles/styles.css" />
исправил

2022-07-27 10:18 UTC, Grikus commented on index.html
> +            </svg>
исправил

2022-07-27 10:32 UTC, Grikus commented on index.html
> +      <div class="section-container">
ну я специально сделал один контейнер для гридов, для хедера и секции со слайдером и описанием
так нельзя разве? а то переделывать там конечно кучу придется

2022-07-27 10:34 UTC, Grikus commented on index.html
> +          <div class="header-background">
не только, на нем гриды висят, паддинги, отступы и наползание на логотип.

2022-07-27 10:49 UTC, Grikus commented on index.html
> +            <div class="header-first-column">
исправил

2022-07-27 10:52 UTC, Grikus commented on styles/styles.css
> +  margin-bottom: 75px;
чтобы снизу отступ был и весь блок имел высоту требуюмую

2022-07-27 10:54 UTC, Grikus commented on styles/styles.css
> +  height: 319px;
min-height? но не особо помогло

2022-08-25 09:29 UTC, closed without merging